version: "3.8"

services:
  node:
    init: true
    tty: true
    image: node:${DOCKER_NODEJS_TAG:-20.10.0}
    command:
    - /bin/sh
    - -c
    - 'cd /app && node --version && npm i --no-optional --no-audit && exec npm run test:watch'
    ports:
    - ${NODE_DEBUG_PORT:-9229}
    volumes:
    - .:/app:cached
    - npm_cache:/root/.npm:delegated
    - npm_cache:/home/node/.npm:delegated

volumes:
  npm_cache:
